algoritmo "valor salario financiamento"
// Função :
// Autor :
// Data : 01/09/2015
// Seção de Declarações 
var
salario,financiamento :real
finc,finn :caractere
inicio
Escreva ("digite seu salario : ")
leia (salario)
Escreva ("digite seu financiamento pretendido : ")
leia (financiamento)
se financiamento <=(5*salario) entao
Escreval (" financiamento concedido ")
senao
Escreval (" financiamento negado ")
fimse
Escreval (" Obrigado por nos consultar ")
fimalgoritmo
