algoritmo "calculo de média aritmética"
// Função : calcular a media aritmética entre dois valores
// Autor :  Allan
// Data : 8/28/2015
// Seção de Declarações 
var
A,B,Media : REAL
inicio
Escreva ("programa que calcula a média aritmética de dois valores.")
Escreva ("Digite um valor : ")
Leia (A)
Escreva ("Digite um valor : ")
Leia (B)
Media <- (A+B)/2
Escreva ("A media entre os dois valores é : ", Media)
fimalgoritmo
