algoritmo "programa que calcula o peso em newton"
// Função : calcular o peso em newton
// Autor : Allan
// Data : 8/28/2015
// Seção de Declarações 
var
massa,gravidade,peso : REAL
inicio
Escreva ("programa que calcula peso em newton")
Escreva (" insira a massa : ")
Leia (massa)
Escreva("insira a gravidade : ")
Leia (gravidade)
peso <- (massa*gravidade)
Escreva ("o peso em newton e igual a :",peso)
fimalgoritmo
