algoritmo "calculo da velocidade media"
// Função :calcular a velocidade media
// Autor :Allan
// Data : 8/28/2015
// Seção de Declarações 
var
espaco,tempo,velocidade : REAL
inicio
Escreval ("para calcular a velocidade media")
Escreva ("digite o espaco : ")
Leia (espaco)
Escreva ("digite o tempo : ")
Leia (tempo)
velocidade <- (espaco)/(tempo)
Escreval ("a velocidade media do percurso e de : ",velocidade)
fimalgoritmo
