algoritmo "Volume de um cilindro"
// Função : Calcular o volume de cilindros
// Autor : Allan
// Data : 8/28/2015
// Seção de Declarações 
var
p,raio,altura,volume : REAL
inicio
Escreval ("para calcular o volume de um cilindro")
p <- 3,1415926535897932384626433832795
Escreva ("digite o raio do cilindro : ")
Leia (raio)
Escreva ("digite a altura do cilindro : ")
Leia (altura)
volume <- ((p)*(raio^2)*(altura))
Escreval ("o volume do cilindro é igual a : ",volume)
fimalgoritmo
