algoritmo "velocidade de propagaçao"
// Função :
// Autor :
// Data : 8/30/2015
// Seção de Declarações 
var
massa,forca,vp : real
inicio
Escreval ("programa que calcula a velocidade de propagaçao de uma onda")
Escreva ("digite a quantidade de massa : ")
Leia (massa)
Escreva ("digite a quantidade de força : ")
Leia (forca)
vp <- raizq(forca/massa)
Escreva ("A velocidade de propagação da onda é de : ",vp)
fimalgoritmo
